FROM nginx
COPY ./conf/adimen.cl.conf /etc/nginx/conf.d/adimen.cl.conf
COPY ./conf/api.adimen.cl.conf /etc/nginx/conf.d/api.adimen.cl.conf
COPY ./conf/cdn.adimen.cl.conf /etc/nginx/conf.d/cdn.adimen.cl.conf
COPY ./cdn/img/*.* /usr/share/nginx/www/assets/img/